language: php

php:
  - 5.4
  - 5.5

before_install:
    - sudo apt-get update > /dev/null
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm

install:
    - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-intl > /dev/null
    - sudo sed -i -e "s,/var/www,$(pwd)/web,g" /etc/apache2/sites-available/default
    - sudo /etc/init.d/apache2 restart
    - mysql -u root -e "CREATE  DATABASE dedipanel; CREATE DATABASE dedipanel_test;"

before_script:
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini

    - cp app/config/dedipanel.yml.dist app/config/dedipanel.yml
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - "sed -i -e 's/database_user: null/database_user: root/' app/config/parameters.yml"
    - "sed -i -e 's/database_name: null/database_name: dedipanel/' app/config/parameters.yml"

    - composer self-update
    - composer install --prefer-source --no-interaction
    - app/console cache:warmup --env=test

#    - sh -e /etc/init.d/xvfb start
#    - export DISPLAY=:99
#    - curl http://selenium-release.storage.googleapis.com/2.41/selenium-server-standalone-2.41.0.jar > selenium.jar
#    - java -jar selenium.jar > /dev/null &
#    - sleep 1

    - features/bootstrap/bootstrap.sh configure
    - features/bootstrap/bootstrap.sh test

script:
  - bin/behat -s installer
  - bin/behat -s users
  - bin/behat -s configs
  - bin/behat -s games_admin
  - bin/behat -s plugins_admin
  - bin/behat -s users_admin
  - bin/behat -s groups_admin
  - bin/behat -s machines
  - bin/behat -s minecraft
  - bin/behat -s steam

after_script:
  - features/bootstrap/bootstrap.sh clean

notifications:
    irc: "irc.freenode.org#dedipanel"
